baseURL: https://minimax.dev/
languageCode: en-us
title: Ramblings on game trees
theme: book
googleAnalytics: UA-10238083-4

# Needed for mermaid/katex shortcodes
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1


menu:
  # before: []
  after:
    - name: "My other writing"
      url: "https://blog.nelhage.com/"
      weight: 10
    - name: "Personal homepage"
      url: "https://nelhage.com/"
      weight: 10
